# Repositories
repositories = [
    "github.com/projectdiscovery/subfinder/v2/cmd/subfinder",
    "github.com/Edu4rdSHL/findomain",
    "github.com/michenriksen/aquatone",
    "github.com/projectdiscovery/dnsx/cmd/dnsx",
    "github.com/tomnomnom/tlsenum/cmd/tlsenum",
    "github.com/projectdiscovery/puredns/cmd/puredns",
    "github.com/maurosoria/dirsearch",
    "github.com/tomnomnom/anew",
    "github.com/tomnomnom/unfurl",
    "github.com/JohnWoodman/katana",
    "github.com/projectdiscovery/shuffledns/cmd/shuffledns"
    "github.com/projectdiscovery/naabu/v2/cmd/naabu"
    "github.com/tomnomnom/assetfinder"
    "github.com/ferreiraklet/airixss"
    "github.com/dwisiswant0/cf-check"
    "github.com/projectdiscovery/chaos-client/cmd/chaos"
    "github.com/edoardottt/cariddi/cmd/cariddi"
    "github.com/hahwul/dalfox/v2"
    "github.com/tomnomnom/hacks/filter-resolved"
    "github.com/ffuf/ffuf/v2"
    "github.com/takshal/freq"
    "github.com/lc/gau/v2/cmd/gau"
    "github.com/tomnomnom/gf"
    "github.com/jaeles-project/gospider"
    "github.com/sensepost/gowitness"
    "github.com/deletescape/goop"
    "github.com/003random/getJS"
    "github.com/hakluke/hakrawler"
    "github.com/hakluke/hakrevdns"
    "github.com/hakluke/haktldextract"
    "github.com/hakluke/haklistgen"
    "github.com/tomnomnom/hacks/html-tool"
    "github.com/projectdiscovery/httpx/cmd/httpx"
    "github.com/jaeles-project/jaeles"
    "github.com/ThreatUnkown/jsubfinder"
    "github.com/Emoe/kxss"
    "github.com/j3ssie/metabigor"
    "github.com/projectdiscovery/notify/cmd/notify"
    ""

]